/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author TAKIYADIP
 */
public class kasir extends javax.swing.JFrame {

    Connection con;
    int dragxmouse;
    int dragymouse;

    public kasir() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));

    }

    public void tampil_tea() {
        com_tea.removeAllItems();
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            Statement stt = con.createStatement();
            String sql = "select tea_name from tea";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                com_tea.addItem(res.getString("tea_name"));
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void tampil_methods() {
        com_coffe.removeAllItems();
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            Statement stt = con.createStatement();
            String sql = "select methods_name from methods";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                com_coffe.addItem(res.getString("methods_name"));
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void tampil_beans() {
        com_coffe.removeAllItems();
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            Statement stt = con.createStatement();
            String sql = "select beans_name from beans";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                com_coffe.addItem(res.getString("beans_name"));
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void tampil_pancong() {
        com_food.removeAllItems();
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            Statement stt = con.createStatement();
            String sql = "select pancong_name from pancong";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                com_food.addItem(res.getString("pancong_name"));
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void tampil_mie() {
        com_food.removeAllItems();
        try {
            koneksi DB = new koneksi();
            DB.config();
            con = DB.con;
            Statement stt = con.createStatement();
            String sql = "select mie_name from indomie";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                com_food.addItem(res.getString("mie_name"));
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spin_tea = new javax.swing.JSpinner();
        com_tea = new javax.swing.JComboBox<>();
        add_tea = new javax.swing.JLabel();
        tea = new javax.swing.JLabel();
        spin_coffe = new javax.swing.JSpinner();
        com_coffe = new javax.swing.JComboBox<>();
        add_coffee = new javax.swing.JLabel();
        beans = new javax.swing.JLabel();
        methods = new javax.swing.JLabel();
        spin_food = new javax.swing.JSpinner();
        com_food = new javax.swing.JComboBox<>();
        add_food = new javax.swing.JLabel();
        indomie = new javax.swing.JLabel();
        pancong = new javax.swing.JLabel();
        namkas = new javax.swing.JLabel();
        jNampem = new javax.swing.JTextField();
        max = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(spin_tea);
        spin_tea.setBounds(310, 620, 60, 30);

        com_tea.setMaximumRowCount(4);
        getContentPane().add(com_tea);
        com_tea.setBounds(200, 590, 240, 30);

        add_tea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/add.png"))); // NOI18N
        add_tea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_teaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_teaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_teaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                add_teaMouseReleased(evt);
            }
        });
        getContentPane().add(add_tea);
        add_tea.setBounds(370, 620, 70, 30);

        tea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/tea.png"))); // NOI18N
        tea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                teaMouseReleased(evt);
            }
        });
        getContentPane().add(tea);
        tea.setBounds(200, 560, 120, 30);
        getContentPane().add(spin_coffe);
        spin_coffe.setBounds(310, 500, 60, 30);

        getContentPane().add(com_coffe);
        com_coffe.setBounds(200, 470, 240, 30);

        add_coffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/add.png"))); // NOI18N
        add_coffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_coffeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_coffeeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_coffeeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                add_coffeeMouseReleased(evt);
            }
        });
        getContentPane().add(add_coffee);
        add_coffee.setBounds(370, 500, 70, 30);

        beans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/beans.png"))); // NOI18N
        beans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beansMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beansMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beansMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beansMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                beansMouseReleased(evt);
            }
        });
        getContentPane().add(beans);
        beans.setBounds(200, 440, 120, 30);

        methods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/methods.png"))); // NOI18N
        methods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                methodsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                methodsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                methodsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                methodsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                methodsMouseReleased(evt);
            }
        });
        getContentPane().add(methods);
        methods.setBounds(320, 440, 120, 30);

        spin_food.setBorder(null);
        getContentPane().add(spin_food);
        spin_food.setBounds(310, 380, 60, 30);

        com_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_foodActionPerformed(evt);
            }
        });
        getContentPane().add(com_food);
        com_food.setBounds(200, 350, 240, 30);

        add_food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/add.png"))); // NOI18N
        add_food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_foodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_foodMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_foodMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                add_foodMouseReleased(evt);
            }
        });
        getContentPane().add(add_food);
        add_food.setBounds(370, 380, 70, 30);

        indomie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/indomie.png"))); // NOI18N
        indomie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indomieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                indomieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                indomieMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                indomieMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                indomieMouseReleased(evt);
            }
        });
        getContentPane().add(indomie);
        indomie.setBounds(320, 320, 120, 30);

        pancong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/pancong.png"))); // NOI18N
        pancong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pancongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pancongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pancongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pancongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pancongMouseReleased(evt);
            }
        });
        getContentPane().add(pancong);
        pancong.setBounds(200, 320, 120, 30);

        namkas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        namkas.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(namkas);
        namkas.setBounds(1070, 170, 120, 20);

        jNampem.setBorder(null);
        jNampem.setOpaque(false);
        jNampem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNampemActionPerformed(evt);
            }
        });
        getContentPane().add(jNampem);
        jNampem.setBounds(110, 250, 200, 30);

        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                maxMouseReleased(evt);
            }
        });
        getContentPane().add(max);
        max.setBounds(1222, -1, 30, 30);

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(1254, -2, 30, 30);

        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 720);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testing/image/kasir.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/close2.png"));
        exit.setIcon(A);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/close.png"));
        exit.setIcon(A);
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/close3.png"));
        exit.setIcon(A);
    }//GEN-LAST:event_exitMousePressed

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/close.png"));
        exit.setIcon(A);
    }//GEN-LAST:event_exitMouseReleased

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - dragxmouse, y - dragymouse);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jNampemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNampemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNampemActionPerformed

    private void com_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_foodActionPerformed

    private void maxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/max.png"));
        max.setIcon(A);
    }//GEN-LAST:event_maxMouseReleased

    private void maxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/max3.png"));
        max.setIcon(A);
    }//GEN-LAST:event_maxMousePressed

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/max.png"));
        max.setIcon(A);
    }//GEN-LAST:event_maxMouseExited

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/max2.png"));
        max.setIcon(A);
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_maxMouseClicked

    private void indomieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indomieMouseClicked
        tampil_mie();
    }//GEN-LAST:event_indomieMouseClicked

    private void indomieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indomieMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/indomie2.png"));
        indomie.setIcon(A);
    }//GEN-LAST:event_indomieMouseEntered

    private void indomieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indomieMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/indomie.png"));
        indomie.setIcon(A);
    }//GEN-LAST:event_indomieMouseExited

    private void indomieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indomieMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/indomie3.png"));
        indomie.setIcon(A);
    }//GEN-LAST:event_indomieMousePressed

    private void indomieMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indomieMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/indomie.png"));
        indomie.setIcon(A);
    }//GEN-LAST:event_indomieMouseReleased

    private void pancongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pancongMouseClicked
        tampil_pancong();
    }//GEN-LAST:event_pancongMouseClicked

    private void pancongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pancongMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/pancong2.png"));
        pancong.setIcon(A);
    }//GEN-LAST:event_pancongMouseEntered

    private void pancongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pancongMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/pancong.png"));
        pancong.setIcon(A);
    }//GEN-LAST:event_pancongMouseExited

    private void pancongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pancongMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/pancong3.png"));
        pancong.setIcon(A);
    }//GEN-LAST:event_pancongMousePressed

    private void pancongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pancongMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/pancong.png"));
        pancong.setIcon(A);
    }//GEN-LAST:event_pancongMouseReleased

    private void beansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseClicked
        tampil_beans();
    }//GEN-LAST:event_beansMouseClicked

    private void beansMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/beans2.png"));
        beans.setIcon(A);
    }//GEN-LAST:event_beansMouseEntered

    private void beansMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/beans.png"));
        beans.setIcon(A);
    }//GEN-LAST:event_beansMouseExited

    private void beansMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/beans3.png"));
        beans.setIcon(A);
    }//GEN-LAST:event_beansMousePressed

    private void beansMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/beans.png"));
        beans.setIcon(A);
    }//GEN-LAST:event_beansMouseReleased

    private void methodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseClicked
        tampil_methods();
    }//GEN-LAST:event_methodsMouseClicked

    private void methodsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/methods2.png"));
        methods.setIcon(A);
    }//GEN-LAST:event_methodsMouseEntered

    private void methodsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/methods.png"));
        methods.setIcon(A);
    }//GEN-LAST:event_methodsMouseExited

    private void methodsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/methods3.png"));
        methods.setIcon(A);
    }//GEN-LAST:event_methodsMousePressed

    private void methodsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/methods.png"));
        methods.setIcon(A);
    }//GEN-LAST:event_methodsMouseReleased

    private void teaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaMouseClicked
        tampil_tea();
    }//GEN-LAST:event_teaMouseClicked

    private void teaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/tea2.png"));
        tea.setIcon(A);
    }//GEN-LAST:event_teaMouseEntered

    private void teaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/tea.png"));
        tea.setIcon(A);
    }//GEN-LAST:event_teaMouseExited

    private void teaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/tea3.png"));
        tea.setIcon(A);    }//GEN-LAST:event_teaMousePressed

    private void teaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/tea.png"));
        tea.setIcon(A);    }//GEN-LAST:event_teaMouseReleased

    private void add_foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_foodMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/add2.png"));
        add_food.setIcon(A);
    }//GEN-LAST:event_add_foodMouseEntered

    private void add_foodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_foodMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_food.setIcon(A);
    }//GEN-LAST:event_add_foodMouseExited

    private void add_foodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_foodMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/add3.png"));
        add_food.setIcon(A);
    }//GEN-LAST:event_add_foodMousePressed

    private void add_foodMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_foodMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_food.setIcon(A);
    }//GEN-LAST:event_add_foodMouseReleased

    private void add_coffeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_coffeeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/add2.png"));
        add_coffee.setIcon(A);
    }//GEN-LAST:event_add_coffeeMouseEntered

    private void add_coffeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_coffeeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_coffee.setIcon(A);
    }//GEN-LAST:event_add_coffeeMouseExited

    private void add_coffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_coffeeMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/add3.png"));
        add_coffee.setIcon(A);
    }//GEN-LAST:event_add_coffeeMousePressed

    private void add_coffeeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_coffeeMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_coffee.setIcon(A);
    }//GEN-LAST:event_add_coffeeMouseReleased

    private void add_teaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_teaMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("image/add2.png"));
        add_tea.setIcon(A);
    }//GEN-LAST:event_add_teaMouseEntered

    private void add_teaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_teaMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_tea.setIcon(A);
    }//GEN-LAST:event_add_teaMouseExited

    private void add_teaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_teaMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("image/add3.png"));
        add_tea.setIcon(A);
    }//GEN-LAST:event_add_teaMousePressed

    private void add_teaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_teaMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("image/add.png"));
        add_tea.setIcon(A);
    }//GEN-LAST:event_add_teaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_coffee;
    private javax.swing.JLabel add_food;
    private javax.swing.JLabel add_tea;
    private javax.swing.JLabel beans;
    private javax.swing.JComboBox<String> com_coffe;
    private javax.swing.JComboBox<String> com_food;
    private javax.swing.JComboBox<String> com_tea;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel indomie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNampem;
    private javax.swing.JLabel max;
    private javax.swing.JLabel methods;
    public javax.swing.JLabel namkas;
    private javax.swing.JLabel pancong;
    private javax.swing.JSpinner spin_coffe;
    private javax.swing.JSpinner spin_food;
    private javax.swing.JSpinner spin_tea;
    private javax.swing.JLabel tea;
    // End of variables declaration//GEN-END:variables
}
